from __future__ import annotations
from html import escape
from pathlib import Path
import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(page_title="Barind Technology & Resilience Dashboard",page_icon="🌾",layout="wide",initial_sidebar_state="expanded")
DATA=Path(__file__).parent; VERSION="1.0"; COVERAGE_CUTOFF=.50

st.markdown('''<style>
.block-container{padding-top:1rem;padding-bottom:2.2rem;max-width:1500px}[data-testid="stMetric"]{background:rgba(148,163,184,.07);border:1px solid rgba(100,116,139,.22);padding:12px 14px;border-radius:14px}.hero{border:1px solid rgba(100,116,139,.22);border-radius:20px;padding:20px 22px;background:linear-gradient(120deg,rgba(37,99,235,.10),rgba(16,185,129,.08),rgba(249,115,22,.07));box-shadow:0 8px 24px rgba(15,23,42,.05);margin-bottom:14px}.hero h1{font-size:2rem;margin:.1rem 0}.hero p{margin:.2rem 0;opacity:.84}.card{border:1px solid rgba(100,116,139,.22);border-radius:16px;padding:14px 16px;margin:7px 0 12px;background:rgba(148,163,184,.045)}.framework{border-radius:16px;padding:14px 15px;min-height:126px;border:1px solid rgba(100,116,139,.22)}.framework h4{margin:0 0 7px}.framework p{margin:0;font-size:.9rem}.t{background:rgba(37,99,235,.09)}.p{background:rgba(22,163,74,.09)}.r{background:rgba(124,58,237,.09)}.e{background:rgba(8,145,178,.09)}.badge{display:inline-block;padding:4px 9px;border-radius:999px;font-size:.75rem;font-weight:700;margin:2px 4px 2px 0;border:1px solid rgba(100,116,139,.20)}.red{background:rgba(220,38,38,.12);color:#b91c1c}.orange{background:rgba(234,88,12,.12);color:#c2410c}.yellow{background:rgba(202,138,4,.14);color:#a16207}.green{background:rgba(22,163,74,.12);color:#15803d}.blue{background:rgba(37,99,235,.12);color:#1d4ed8}.purple{background:rgba(124,58,237,.12);color:#6d28d9}.gray{background:rgba(100,116,139,.12);color:#475569}.action{border:1px solid rgba(100,116,139,.22);border-left:7px solid #64748b;border-radius:16px;padding:15px 17px;margin:10px 0 16px}.action-red{border-left-color:#dc2626}.action-orange{border-left-color:#ea580c}.action-yellow{border-left-color:#ca8a04}.action-blue{border-left-color:#2563eb}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 16px;margin-top:9px}.item{font-size:.88rem;line-height:1.42}.flow{display:flex;gap:8px;flex-wrap:wrap;margin:9px 0 16px}.step{flex:1 1 135px;border:1px solid rgba(100,116,139,.22);border-radius:13px;padding:10px;text-align:center;font-size:.85rem;font-weight:650;background:rgba(148,163,184,.05)}.source{font-size:.79rem;opacity:.72;margin-top:-4px}.soft{height:1px;background:rgba(100,116,139,.18);margin:12px 0 18px}@media(max-width:780px){.hero h1{font-size:1.55rem}.grid{grid-template-columns:1fr}.framework{min-height:auto}}
</style>''',unsafe_allow_html=True)

lang=st.sidebar.radio("Language / ভাষা",["English","বাংলা"],horizontal=True,key="language")
def L(en,bn): return bn if lang=="বাংলা" else en
def uname(x): return {"Mahadebpur":"মহাদেবপুর","Sapahar":"সাপাহার"}.get(x,x) if lang=="বাংলা" else x
def b(text,tone="gray"): return f"<span class='badge {tone}'>{escape(str(text))}</span>"
def n(x,d=1): return "—" if pd.isna(x) else f"{float(x):,.{d}f}"
def ni(x): return "—" if pd.isna(x) else f"{int(round(float(x))):,}"
def pct(x,d=1): return "—" if pd.isna(x) else f"{float(x)*100:.{d}f}%"
def source(txt): st.markdown(f"<div class='source'><b>{escape(L('Source','উৎস'))}:</b> {escape(txt)}</div>",unsafe_allow_html=True)
def figstyle(fig,h=None):
    fig.update_layout(margin=dict(l=20,r=20,t=55,b=20),paper_bgcolor="rgba(0,0,0,0)",plot_bgcolor="rgba(0,0,0,0)",legend_title_text="")
    if h: fig.update_layout(height=h)
    fig.update_xaxes(showgrid=False); fig.update_yaxes(gridcolor="rgba(148,163,184,.18)")
    return fig
def place(df):
    o=df.copy(); o["Upazila_display"]=o["upazila"].map(uname) if "upazila" in o else ""; return o
COLORS={uname("Mahadebpur"):"#2563eb",uname("Sapahar"):"#f97316"}
def card(title,body,icon="ℹ️",badges=None):
    badges=badges or []; bh="".join(b(t,c) for t,c in badges)
    st.markdown(f"<div class='card'><b>{icon} {escape(title)}</b><div>{bh}</div><div style='margin-top:6px'>{escape(body)}</div></div>",unsafe_allow_html=True)

REQ=["v02_monthly_panel.csv","v01_bmda_t_panel.csv","v01_warpo_baseline.csv","v01_scorecard.csv","v01_bbs_productivity_context.csv","v01_monthly_climate_reference.csv","modis_interpolation_audit.csv","modis_qa_comparison_audit.csv","upazila_locations.csv"]
@st.cache_data
def load():
    miss=[x for x in REQ if not (DATA/x).exists()]
    if miss: raise FileNotFoundError("Missing: "+", ".join(miss))
    return tuple(pd.read_csv(DATA/x) for x in REQ)
try: panel,bmda,warpo,score,bbs,climref,interp,qa,loc=load()
except Exception as ex: st.error(L("Dashboard data could not be loaded.","ড্যাশবোর্ড ডেটা লোড করা যায়নি।")); st.code(str(ex)); st.stop()

panel["date_dt"]=pd.to_datetime(panel["date"].astype(str)+"-01"); panel=panel.sort_values(["upazila","date_dt"]).reset_index(drop=True)
for pre,col in [("rain","rainfall_mm"),("ndvi","NDVI_monthly"),("evi","EVI_monthly")]:
    mu=panel.groupby(["upazila","month"])[col].transform("mean"); sd=panel.groupby(["upazila","month"])[col].transform("std").replace(0,np.nan); panel[f"{pre}_z"]=(panel[col]-mu)/sd
panel["quality_key"]=np.select([panel.MODIS_source_status.eq("interpolated"),panel.MODIS_coverage_proxy.lt(COVERAGE_CUTOFF)],["interpolated","low"],default="high")
for k in range(4):
    g=panel.groupby("upazila",sort=False)
    for pre,col in [("ndvi","ndvi_z"),("evi","evi_z")]: panel[f"{pre}_z_lag{k}"]=g[col].shift(-k)
    for pre,col in [("ndvi","NDVI_monthly"),("evi","EVI_monthly")]: panel[f"{pre}_value_lag{k}"]=g[col].shift(-k)
    panel[f"target_status_lag{k}"]=g["MODIS_source_status"].shift(-k); panel[f"target_cov_lag{k}"]=g["MODIS_coverage_proxy"].shift(-k); panel[f"target_quality_lag{k}"]=g["quality_key"].shift(-k)

def add_runs(df,thr):
    out=[]
    for _,g in df.sort_values(["upazila","date_dt"]).groupby("upazila",sort=False):
        x=g.copy(); sh=x.rain_z.le(thr)&x.rain_z.notna(); rid=sh.ne(sh.shift(fill_value=False)).cumsum(); rl=sh.groupby(rid).transform("sum").astype(int); rp=sh.groupby(rid).cumcount()+1
        x["dry_shock"]=sh; x["shock_len"]=np.where(sh,rl,0).astype(int); x["shock_pos"]=np.where(sh,rp,0).astype(int); x["shock_start"]=sh&x.shock_pos.eq(1); out.append(x)
    return pd.concat(out,ignore_index=True)
def duration_mask(df,key):
    if key=="single": return df.dry_shock&df.shock_len.eq(1)
    if key=="two": return df.dry_shock&df.shock_len.eq(2)
    if key=="three": return df.dry_shock&df.shock_len.ge(3)
    return df.dry_shock
def qfilter(df,mode):
    if mode=="observed": return df[df.MODIS_source_status.eq("observed")].copy()
    if mode=="coverage": return df[df.MODIS_source_status.eq("observed")&df.MODIS_coverage_proxy.ge(COVERAGE_CUTOFF)].copy()
    return df.copy()
def tqfilter(df,mode,k):
    if mode=="observed": return df[df[f"target_status_lag{k}"].eq("observed")].copy()
    if mode=="coverage": return df[df[f"target_status_lag{k}"].eq("observed")&df[f"target_cov_lag{k}"].ge(COVERAGE_CUTOFF)].copy()
    return df.copy()
def qname(x): return {"high":L("Observed · higher coverage","পর্যবেক্ষিত · বেশি কভারেজ"),"low":L("Observed · lower coverage","পর্যবেক্ষিত · কম কভারেজ"),"interpolated":L("Interpolated","ইন্টারপোলেটেড")}.get(x,x)

SEASONS={"all":list(range(1,13)),"dry":[11,12,1,2,3,4],"pre":[5],"monsoon":[6,7,8,9,10]}
SL={"all":L("All months","সব মাস"),"dry":L("Dry / Rabi–Boro window (Nov–Apr)","শুষ্ক / রবি–বোরো সময় (নভে–এপ্রি)"),"pre":L("Pre-monsoon (May)","প্রাক্-মৌসুম (মে)"),"monsoon":L("Monsoon / Aman window (Jun–Oct)","মৌসুম / আমন সময় (জুন–অক্টো)")}
MN_EN={1:"Jan",2:"Feb",3:"Mar",4:"Apr",5:"May",6:"Jun",7:"Jul",8:"Aug",9:"Sep",10:"Oct",11:"Nov",12:"Dec"}; MN_BN={1:"জানু",2:"ফেব",3:"মার্চ",4:"এপ্রি",5:"মে",6:"জুন",7:"জুলাই",8:"আগ",9:"সেপ্টে",10:"অক্টো",11:"নভে",12:"ডিসে"}; MN=MN_BN if lang=="বাংলা" else MN_EN

st.sidebar.markdown(f"### {L('Dashboard controls','ড্যাশবোর্ড নিয়ন্ত্রণ')}")
view=st.sidebar.radio(L("View mode","ভিউ মোড"),["Executive","Research"],format_func=lambda x:L("Executive / decision view","সিদ্ধান্তগ্রহণকারী ভিউ") if x=="Executive" else L("Research / technical view","গবেষণা / কারিগরি ভিউ"),key="view")
ups=sorted(panel.upazila.unique()); selected=st.sidebar.multiselect(L("Upazila","উপজেলা"),ups,default=ups,format_func=uname,key="upazilas")
if not selected: st.warning(L("Select at least one upazila.","অন্তত একটি উপজেলা নির্বাচন করুন।")); st.stop()
years=st.sidebar.slider(L("Climate & vegetation year range","জলবায়ু ও উদ্ভিদ বছরসীমা"),int(panel.year.min()),int(panel.year.max()),(int(panel.year.min()),int(panel.year.max())),key="years")
season=st.sidebar.selectbox(L("Calendar / broad crop-season window","ক্যালেন্ডার / বিস্তৃত ফসল-মৌসুম সময়"),list(SEASONS),format_func=lambda x:SL[x],key="season"); months=SEASONS[season]
st.sidebar.caption(L("Broad analytical windows, not exact crop phenology.","এগুলো বিস্তৃত বিশ্লেষণকাল; সুনির্দিষ্ট ফসল-ফেনোলজি নয়।"))
qmode=st.sidebar.selectbox(L("Vegetation-data filter","উদ্ভিদ ডেটা ফিল্টার"),["all","observed","coverage"],format_func=lambda x:{"all":L("All finalized MODIS values","সব চূড়ান্ত MODIS মান"),"observed":L("Observed only","শুধু পর্যবেক্ষিত"),"coverage":L("Observed + coverage proxy ≥50%","পর্যবেক্ষিত + কভারেজ প্রক্সি ≥৫০%")}[x],key="qmode")
if st.sidebar.button(L("Reset filters","ফিল্টার রিসেট"),use_container_width=True):
    for k in ["view","upazilas","years","season","qmode"]: st.session_state.pop(k,None)
    st.rerun()
with st.sidebar.expander(L("Terminology: what does it mean?","পরিভাষা: এর অর্থ কী?")):
    terms=[("NDVI",L("Satellite vegetation greenness indicator; not direct crop yield.","স্যাটেলাইট উদ্ভিদ-সবুজত্ব সূচক; সরাসরি ফসল ফলন নয়।")),("EVI",L("Another satellite vegetation indicator.","আরেকটি স্যাটেলাইট উদ্ভিদ সূচক।")),(L("Rainfall anomaly","বৃষ্টিপাতের বিচ্যুতি"),L("How unusual rainfall was versus the normal value for the same month.","একই মাসের স্বাভাবিক মানের তুলনায় বৃষ্টি কতটা অস্বাভাবিক।")),(L("Z-score","Z-স্কোর"),L("Standard deviations above or below the historical monthly mean.","ঐতিহাসিক মাসিক গড় থেকে কত স্ট্যান্ডার্ড ডিভিয়েশন উপরে/নিচে।")),("DTW",L("Deep Tube Well for groundwater abstraction/irrigation.","ভূগর্ভস্থ পানি উত্তোলন/সেচে ব্যবহৃত গভীর নলকূপ।")),(L("Service area","সেবা এলাকা"),L("Reported area served; not necessarily unique irrigated land.","প্রতিবেদিত সেবা এলাকা; এটি আবশ্যিকভাবে স্বতন্ত্র সেচকৃত জমি নয়।")),(L("Resilience","সহনশীলতা"),L("How vegetation withstands and returns toward normal after adverse climate conditions.","প্রতিকূল জলবায়ুতে উদ্ভিদ কতটা টিকে থাকে ও স্বাভাবিকতার দিকে ফিরে আসে।"))]
    for a,c in terms: st.markdown(f"**{a}** — {c}")
st.sidebar.markdown("---"); st.sidebar.caption(L("CHIRPS/MODIS: 2001–2025 · BMDA: 2017–18 to 2020–21 · WARPO/IWM: historical/study-period · BBS: district context","CHIRPS/MODIS: ২০০১–২০২৫ · BMDA: ২০১৭–১৮ থেকে ২০২০–২১ · WARPO/IWM: ঐতিহাসিক/গবেষণাকালীন · BBS: জেলা প্রেক্ষাপট"))

f=panel[panel.upazila.isin(selected)&panel.year.between(*years)&panel.month.isin(months)].copy(); fv=qfilter(f,qmode)
if f.empty: st.warning(L("No observations match the filters.","ফিল্টারে কোনো পর্যবেক্ষণ নেই।")); st.stop()

st.markdown(f'''<div class="hero"><div style="font-size:.78rem;font-weight:800;opacity:.7">{escape(L("EVIDENCE-TO-ACTION RESEARCH DASHBOARD","প্রমাণ থেকে করণীয় গবেষণা ড্যাশবোর্ড"))}</div><h1>{escape(L("Barind Technology & Resilience Dashboard","বরেন্দ্র প্রযুক্তি ও সহনশীলতা ড্যাশবোর্ড"))}</h1><p><b>{escape(L("Afnan Agricultural Technology & Resilience Model","আফনান কৃষি প্রযুক্তি ও সহনশীলতা মডেল"))}</b></p><p>{escape(L("Mahadebpur and Sapahar, Naogaon","মহাদেবপুর ও সাপাহার, নওগাঁ"))}</p><div style="margin-top:9px">{b(L("Version 1.0","সংস্করণ ১.০"),"blue")}{b(L("Observational pilot","পর্যবেক্ষণমূলক পাইলট"),"purple")}{b(L("Satellite data through Dec 2025","স্যাটেলাইট ডেটা ডিসেম্বর ২০২৫ পর্যন্ত"),"green")}</div></div>''',unsafe_allow_html=True)
st.info(L("NDVI/EVI are vegetation proxies, not direct crop yield. Historical groundwater evidence is not a current groundwater measurement. The derived stress score is not official IWM WSI, and U=f(T,P,R,E) is not empirically estimated here.","NDVI/EVI উদ্ভিদের প্রক্সি, সরাসরি ফসল ফলন নয়। ঐতিহাসিক ভূগর্ভস্থ পানির প্রমাণ বর্তমান মাপ নয়। ডেরাইভড স্ট্রেস স্কোর সরকারি IWM WSI নয় এবং এখানে U=f(T,P,R,E) প্রায়োগিকভাবে অনুমান করা হয়নি।"))
fc=st.columns(4); frameworks=[("t","⚙️",L("T — Technology","T — প্রযুক্তি"),L("BMDA DTW/LLP infrastructure and irrigation diagnostics.","BMDA DTW/LLP অবকাঠামো ও সেচ নির্ণায়ক।")),("p","🌾",L("P — Productivity proxy","P — উৎপাদনশীলতার প্রক্সি"),L("MODIS NDVI/EVI; BBS crop data are district context only.","MODIS NDVI/EVI; BBS ফসল ডেটা শুধু জেলা প্রেক্ষাপট।")),("r","🛡️",L("R — Resilience","R — সহনশীলতা"),L("Vegetation response, persistence and recovery around rainfall shocks.","বৃষ্টির ধাক্কায় উদ্ভিদ প্রতিক্রিয়া, স্থায়িত্ব ও পুনরুদ্ধার।")),("e","💧",L("E — Resource pressure","E — সম্পদচাপ"),L("Groundwater depth, water stress and demand pressure.","ভূগর্ভস্থ পানির গভীরতা, পানি-চাপ ও চাহিদা।"))]
for col,(cls,ic,ti,bo) in zip(fc,frameworks):
    with col: st.markdown(f"<div class='framework {cls}'><h4>{ic} {escape(ti)}</h4><p>{escape(bo)}</p></div>",unsafe_allow_html=True)
st.markdown("<div class='soft'></div>",unsafe_allow_html=True)

tabs=st.tabs([L("Overview","সারসংক্ষেপ"),L("Climate & Vegetation","জলবায়ু ও উদ্ভিদ"),L("Irrigation Technology","সেচ প্রযুক্তি"),L("Water Stress","পানির চাপ"),L("Resilience","সহনশীলতা"),L("Actions","করণীয়"),L("Data, Methods & Downloads","ডেটা, পদ্ধতি ও ডাউনলোড")])
# ---------------- OVERVIEW ----------------
with tabs[0]:
    st.subheader(L("Executive diagnosis","সিদ্ধান্তমূলক সারসংক্ষেপ"))
    c=st.columns(4); c[0].metric(L("Monthly climate records","মাসিক জলবায়ু রেকর্ড"),f"{len(panel):,}"); c[1].metric(L("Climate period","জলবায়ু সময়কাল"),"2001–2025"); c[2].metric(L("Interpolated MODIS months","ইন্টারপোলেটেড MODIS মাস"),int(panel.MODIS_source_status.eq("interpolated").sum())); c[3].metric(L("Study upazilas","গবেষণা উপজেলা"),panel.upazila.nunique())
    st.markdown(f"#### {L('Data freshness','ডেটার সময়কাল')}")
    st.markdown(b(L("CHIRPS/MODIS · through Dec 2025","CHIRPS/MODIS · ডিসে ২০২৫ পর্যন্ত"),"green")+b(L("BMDA · 2017–18 to 2020–21","BMDA · ২০১৭–১৮ থেকে ২০২০–২১"),"blue")+b(L("WARPO/IWM · historical/study-period","WARPO/IWM · ঐতিহাসিক/গবেষণাকালীন"),"yellow")+b(L("BBS · district context","BBS · জেলা প্রেক্ষাপট"),"gray"),unsafe_allow_html=True)

    latest=score[score.upazila.isin(selected)].copy(); latest["coverage_pct"]=latest.dtw_coverage*100; latest["vh_pct"]=latest.very_high_stress_union_share*100
    a1,a2=st.columns([1.05,1.25])
    with a1:
        lm=loc[loc.upazila.isin(selected)]
        if not lm.empty: st.map(lm,latitude="lat",longitude="lon",size=9000,zoom=8); st.caption(L("Audited ADM3 centroid locations.","অডিটকৃত ADM3 কেন্দ্রবিন্দু অবস্থান।"))
    with a2:
        d=latest[["upazila","latest_dtw_units","latest_dtw_area_ha","coverage_pct","gwt_max_depth_m","vh_pct","stress_score_0_100"]].copy(); d.upazila=d.upazila.map(uname)
        d=d.rename(columns={"upazila":L("Upazila","উপজেলা"),"latest_dtw_units":L("Latest recorded DTWs","সর্বশেষ রেকর্ডকৃত DTW"),"latest_dtw_area_ha":L("Reported DTW service area (ha)","প্রতিবেদিত DTW সেবা এলাকা (হা)"),"coverage_pct":L("Service-area ratio (%)","সেবা-এলাকা অনুপাত (%)"),"gwt_max_depth_m":L("Historical max GWT depth (m)","ঐতিহাসিক সর্বোচ্চ GWT গভীরতা (মি)"),"vh_pct":L("Very-high-stress union share (%)","অতি-উচ্চ-চাপ ইউনিয়নের অংশ (%)"),"stress_score_0_100":L("Derived stress score (0–100)","ডেরাইভড স্ট্রেস স্কোর (০–১০০)")})
        st.dataframe(d.round(1),hide_index=True,use_container_width=True)
        st.caption(L("Service-area ratios are diagnostic and may include overlap. The 0–100 score is derived, not official WSI.","সেবা-এলাকা অনুপাত নির্ণায়ক এবং ওভারল্যাপ থাকতে পারে। ০–১০০ স্কোরটি ডেরাইভড, সরকারি WSI নয়।"))

    st.markdown(f"#### {L('Historical water evidence vs satellite-era signal','ঐতিহাসিক পানি-প্রমাণ বনাম স্যাটেলাইট-যুগের সংকেত')}")
    x1,x2=st.columns(2)
    with x1:
        lines=[]
        for _,r in warpo[warpo.upazila.isin(selected)].iterrows(): lines.append(f"{uname(r.upazila)}: {L('GWT depth','GWT গভীরতা')} {n(r.gwt_min_depth_m)}–{n(r.gwt_max_depth_m)} m; {L('very-high/high-stress unions','অতি-উচ্চ/উচ্চ-চাপ ইউনিয়ন')} {ni(r.very_high_stress_unions)}/{ni(r.high)}.")
        card(L("Historical / study-period water evidence","ঐতিহাসিক / গবেষণাকালীন পানি-প্রমাণ")," ".join(lines),"💧",[(L("Historical baseline","ঐতিহাসিক ভিত্তি"),"yellow")])
    with x2:
        lines=[]
        for up in selected:
            ann=panel[panel.upazila.eq(up)].groupby("year").agg(rain=("rainfall_mm","sum"),ndvi=("NDVI_monthly","mean")); base=ann.loc[(ann.index>=2001)&(ann.index<=2020)].mean(); recent=ann.loc[(ann.index>=2021)&(ann.index<=2025)].mean(); rc=(recent.rain/base.rain-1)*100; dc=recent.ndvi-base.ndvi
            lines.append(f"{uname(up)}: {L('2021–25 rainfall vs 2001–20','২০২১–২৫ বৃষ্টি বনাম ২০০১–২০')} {rc:+.1f}%; {L('mean NDVI difference','গড় NDVI পার্থক্য')} {dc:+.3f}.")
        card(L("Satellite signal through 2025","২০২৫ পর্যন্ত স্যাটেলাইট সংকেত")," ".join(lines)+" "+L("This does not update groundwater measurements.","এটি ভূগর্ভস্থ পানির মাপ হালনাগাদ করে না।"),"🛰️",[(L("Descriptive signal","বর্ণনামূলক সংকেত"),"blue")])

    st.markdown(f"#### {L('Key findings','মূল পর্যবেক্ষণ')}")
    if {"Mahadebpur","Sapahar"}.issubset(selected):
        w=warpo.set_index("upazila")
        st.markdown(L(f"- Historical/study-period evidence shows a stronger groundwater-stress signal in Sapahar: {int(w.loc['Sapahar','very_high_stress_unions'])} very-high-stress unions versus {int(w.loc['Mahadebpur','very_high_stress_unions'])} in Mahadebpur.",f"- ঐতিহাসিক/গবেষণাকালীন প্রমাণে সাপাহারে চাপ বেশি: {int(w.loc['Sapahar','very_high_stress_unions'])}টি অতি-উচ্চ-চাপ ইউনিয়ন, মহাদেবপুরে {int(w.loc['Mahadebpur','very_high_stress_unions'])}টি।"))
        st.markdown(L(f"- Historical maximum GWT depth is {w.loc['Sapahar','gwt_max_depth_m']:.1f} m in Sapahar versus {w.loc['Mahadebpur','gwt_max_depth_m']:.1f} m in Mahadebpur.",f"- ঐতিহাসিক সর্বোচ্চ GWT গভীরতা সাপাহারে {w.loc['Sapahar','gwt_max_depth_m']:.1f} মি, মহাদেবপুরে {w.loc['Mahadebpur','gwt_max_depth_m']:.1f} মি।"))
    st.markdown(L("- NDVI/EVI should be read as vegetation condition proxies, not direct focal-upazila crop yield.","- NDVI/EVI-কে উদ্ভিদের অবস্থা-প্রক্সি হিসেবে পড়তে হবে, ফোকাল উপজেলার সরাসরি ফসল ফলন হিসেবে নয়।"))

    st.markdown(f"#### {L('T/P/R/E profile — no artificial overall score','T/P/R/E প্রোফাইল — কোনো কৃত্রিম সামগ্রিক স্কোর নয়')}")
    ds=add_runs(panel,-1.0); pcs=st.columns(len(selected))
    for col,up in zip(pcs,selected):
        with col:
            sr=score[score.upazila.eq(up)].iloc[0]; pmean=fv[fv.upazila.eq(up)].NDVI_monthly.mean(); rr=ds[ds.upazila.eq(up)&ds.year.between(*years)&ds.month.isin(months)&ds.dry_shock].ndvi_z_lag1.mean()
            st.markdown(f"<div class='card'><b>📍 {escape(uname(up))}</b><div>⚙️ T: {ni(sr.latest_dtw_units)} DTWs; {pct(sr.dtw_coverage)} {escape(L('service-area ratio','সেবা-এলাকা অনুপাত'))}</div><div>🌾 P: {escape(L('mean selected NDVI','নির্বাচিত গড় NDVI'))} {n(pmean,3)}</div><div>🛡️ R: {escape(L('exploratory +1m dry-shock NDVI response','অনুসন্ধানমূলক +১মাস শুষ্ক-ধাক্কা NDVI প্রতিক্রিয়া'))} {n(rr,2)} z</div><div>💧 E: {escape(L('historical max GWT','ঐতিহাসিক সর্বোচ্চ GWT'))} {n(sr.gwt_max_depth_m)} m; {escape(L('derived stress','ডেরাইভড চাপ'))} {n(sr.stress_score_0_100)}</div></div>",unsafe_allow_html=True)
    st.caption(L("R is exploratory; no causal technology effect or overall welfare score is claimed.","R অনুসন্ধানমূলক; কোনো কারণগত প্রযুক্তি প্রভাব বা সামগ্রিক কল্যাণ স্কোর দাবি করা হয় না।"))

    ann=f.groupby(["upazila","year"],as_index=False).agg(rain=("rainfall_mm","sum")); ann=place(ann); annv=fv.groupby(["upazila","year"],as_index=False).agg(ndvi=("NDVI_monthly","mean")); annv=place(annv)
    z1,z2=st.columns(2)
    with z1:
        fg=px.line(ann,x="year",y="rain",color="Upazila_display",markers=True,color_discrete_map=COLORS,labels={"year":L("Year","বছর"),"rain":L("Rainfall across selected months (mm)","নির্বাচিত মাসের বৃষ্টিপাত (মিমি)"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Rainfall across selected analytical window","নির্বাচিত বিশ্লেষণকালে বৃষ্টিপাত")); st.plotly_chart(figstyle(fg),use_container_width=True); source("CHIRPS v3")
    with z2:
        fg=px.line(annv,x="year",y="ndvi",color="Upazila_display",markers=True,color_discrete_map=COLORS,labels={"year":L("Year","বছর"),"ndvi":L("Mean NDVI","গড় NDVI"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Mean NDVI across selected analytical window","নির্বাচিত বিশ্লেষণকালে গড় NDVI")); st.plotly_chart(figstyle(fg),use_container_width=True); source("MODIS MOD13Q1")

# ---------------- CLIMATE & VEGETATION ----------------
with tabs[1]:
    st.subheader(L("Climate and vegetation signal","জলবায়ু ও উদ্ভিদ সংকেত")); st.caption(L("Climate filters apply here; the vegetation quality filter does not remove rainfall from the rainfall-only chart.","জলবায়ু ফিল্টার এখানে প্রযোজ্য; উদ্ভিদ মান-ফিল্টার বৃষ্টির চার্ট থেকে বৃষ্টি বাদ দেয় না।"))
    vidx=st.radio(L("Vegetation indicator","উদ্ভিদ সূচক"),["NDVI","EVI"],horizontal=True,key="vidx"); vcol="NDVI_monthly" if vidx=="NDVI" else "EVI_monthly"; vz="ndvi_z" if vidx=="NDVI" else "evi_z"
    c1,c2=st.columns(2)
    with c1:
        d=place(f); fg=px.line(d,x="date_dt",y="rainfall_mm",color="Upazila_display",color_discrete_map=COLORS,labels={"date_dt":L("Date","তারিখ"),"rainfall_mm":L("Monthly rainfall (mm)","মাসিক বৃষ্টিপাত (মিমি)"),"Upazila_display":L("Upazila","উপজেলা")},title=L("What happened to monthly rainfall?","মাসিক বৃষ্টিপাতে কী ঘটেছে?")); st.plotly_chart(figstyle(fg),use_container_width=True); source("CHIRPS v3")
    with c2:
        if fv.empty: st.warning(L("No vegetation observations remain after the quality filter.","মান-ফিল্টারের পর কোনো উদ্ভিদ পর্যবেক্ষণ নেই।"))
        else:
            d=place(fv); d["Quality"]=d.quality_key.map(qname); fg=px.line(d,x="date_dt",y=vcol,color="Upazila_display",color_discrete_map=COLORS,hover_data={"Quality":True,"MODIS_coverage_proxy":":.1%","MODIS_source_status":True},labels={"date_dt":L("Date","তারিখ"),vcol:vidx,"Upazila_display":L("Upazila","উপজেলা"),"Quality":L("Data quality","ডেটার মান"),"MODIS_coverage_proxy":L("Coverage proxy","কভারেজ প্রক্সি")},title=L(f"How did {vidx} change over time?",f"সময়ের সাথে {vidx} কীভাবে বদলেছে?")); st.plotly_chart(figstyle(fg),use_container_width=True); source("MODIS MOD13Q1")
    st.markdown(f"#### {L('Calendar-month normal pattern','ক্যালেন্ডার-মাসের স্বাভাবিক ধরন')}")
    cr=f.groupby(["upazila","month"],as_index=False).rainfall_mm.mean(); cv=fv.groupby(["upazila","month"],as_index=False)[vcol].mean() if not fv.empty else pd.DataFrame(); order=[MN[m] for m in months]; cr["Month"]=pd.Categorical(cr.month.map(MN),categories=order,ordered=True); cr=place(cr.sort_values("Month"))
    q1,q2=st.columns(2)
    with q1:
        fg=px.bar(cr,x="Month",y="rainfall_mm",color="Upazila_display",barmode="group",color_discrete_map=COLORS,labels={"Month":L("Month","মাস"),"rainfall_mm":L("Mean rainfall (mm)","গড় বৃষ্টিপাত (মিমি)"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Typical rainfall by calendar month","ক্যালেন্ডার মাস অনুযায়ী সাধারণ বৃষ্টিপাত")); st.plotly_chart(figstyle(fg),use_container_width=True); source("CHIRPS v3")
    with q2:
        if not cv.empty:
            cv["Month"]=pd.Categorical(cv.month.map(MN),categories=order,ordered=True); cv=place(cv.sort_values("Month")); fg=px.line(cv,x="Month",y=vcol,color="Upazila_display",markers=True,color_discrete_map=COLORS,labels={"Month":L("Month","মাস"),vcol:L(f"Mean {vidx}",f"গড় {vidx}"),"Upazila_display":L("Upazila","উপজেলা")},title=L(f"Typical {vidx} by calendar month",f"ক্যালেন্ডার মাস অনুযায়ী সাধারণ {vidx}")); st.plotly_chart(figstyle(fg),use_container_width=True); source("MODIS MOD13Q1")
    st.markdown(f"#### {L('Compared with normal: rainfall vs vegetation anomaly','স্বাভাবিকের তুলনা: বৃষ্টি বনাম উদ্ভিদ বিচ্যুতি')}")
    sc=fv.dropna(subset=["rain_z",vz]).copy()
    if not sc.empty:
        sc=place(sc); sc["Quality"]=sc.quality_key.map(qname); fg=px.scatter(sc,x="rain_z",y=vz,color="Upazila_display",opacity=.68,color_discrete_map=COLORS,hover_data={"date":True,"rainfall_mm":":.1f",vcol:":.3f","Quality":True,"MODIS_coverage_proxy":":.1%"},labels={"rain_z":L("Rainfall anomaly (z-score)","বৃষ্টির বিচ্যুতি (z-স্কোর)"),vz:L(f"{vidx} anomaly (z-score)",f"{vidx} বিচ্যুতি (z-স্কোর)"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Same-month association — descriptive, not causal","একই-মাসের সম্পর্ক — বর্ণনামূলক, কারণগত নয়")); fg.add_vline(x=0,line_dash="dot",line_color="#64748b"); fg.add_hline(y=0,line_dash="dot",line_color="#64748b"); st.plotly_chart(figstyle(fg,500),use_container_width=True); source("CHIRPS v3 + MODIS MOD13Q1")
        if view=="Research":
            rows=[{L("Upazila","উপজেলা"):uname(up),L("Pearson r","পিয়ারসন r"):g.rain_z.corr(g[vz]),L("Observations","পর্যবেক্ষণ"):len(g)} for up,g in sc.groupby("upazila")]; st.dataframe(pd.DataFrame(rows).round(3),hide_index=True,use_container_width=False)
        st.caption(L("Weak same-month association does not mean rainfall is unimportant; vegetation may respond later. Test lags in the Resilience tab.","একই-মাসের দুর্বল সম্পর্ক বৃষ্টিকে অপ্রাসঙ্গিক করে না; উদ্ভিদ পরে প্রতিক্রিয়া দেখাতে পারে। সহনশীলতা ট্যাবে বিলম্ব পরীক্ষা করুন।"))
# ---------------- IRRIGATION TECHNOLOGY ----------------
with tabs[2]:
    st.subheader(L("Irrigation technology (T)","সেচ প্রযুক্তি (T)")); st.warning(L("This tab uses BMDA focal observations for 2017–18 to 2020–21. The climate year slider does not change these technology records.","এই ট্যাবে ২০১৭–১৮ থেকে ২০২০–২১ সালের BMDA ফোকাল পর্যবেক্ষণ ব্যবহৃত হয়েছে। জলবায়ু বছরসীমা এই প্রযুক্তি রেকর্ড পরিবর্তন করে না।"))
    bm=place(bmda[bmda.upazila.isin(selected)].copy()); tc=st.columns(len(selected))
    for col,up in zip(tc,selected):
        with col:
            g=bmda[bmda.upazila.eq(up)]; last=g.iloc[-1]; llp=g.dropna(subset=["llp_units"])
            st.markdown(f"**📍 {uname(up)}**"); a,bx,c=st.columns(3); a.metric(L("Latest DTWs","সর্বশেষ DTW"),ni(last.dtw_units)); bx.metric(L("Reported service area","প্রতিবেদিত সেবা এলাকা"),f"{ni(last.dtw_irrigated_area_ha)} ha"); c.metric(L("Service-area ratio","সেবা-এলাকা অনুপাত"),pct(last.dtw_coverage_of_irrigable_area))
            if not llp.empty:
                lr=llp.iloc[-1]; st.caption(L(f"Latest available LLP: {ni(lr.llp_units)} units, {ni(lr.llp_irrigated_area_ha)} ha reported service area.",f"সর্বশেষ উপলভ্য LLP: {ni(lr.llp_units)} ইউনিট, {ni(lr.llp_irrigated_area_ha)} হা প্রতিবেদিত সেবা এলাকা।"))
    t1,t2=st.columns(2)
    with t1:
        fg=px.line(bm,x="fy",y="dtw_units",color="Upazila_display",markers=True,color_discrete_map=COLORS,labels={"fy":L("BMDA fiscal year","BMDA অর্থবছর"),"dtw_units":L("DTW units","DTW ইউনিট"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Recorded BMDA deep-tube-well units","রেকর্ডকৃত BMDA গভীর নলকূপ ইউনিট")); st.plotly_chart(figstyle(fg),use_container_width=True); source("BMDA Annual Reports")
    with t2:
        fg=px.line(bm,x="fy",y="dtw_coverage_of_irrigable_area",color="Upazila_display",markers=True,color_discrete_map=COLORS,labels={"fy":L("BMDA fiscal year","BMDA অর্থবছর"),"dtw_coverage_of_irrigable_area":L("DTW service area / irrigable baseline","DTW সেবা এলাকা / সেচযোগ্য ভিত্তি"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Reported DTW service-area ratio","প্রতিবেদিত DTW সেবা-এলাকা অনুপাত")); fg.update_yaxes(tickformat=".0%"); st.plotly_chart(figstyle(fg),use_container_width=True); source("BMDA Annual Reports + WARPO/IWM baseline")
    st.info(L("A higher service-area ratio does not automatically mean better sustainability. Reported service areas may overlap, and groundwater-based irrigation can increase resource pressure in stressed aquifers.","বেশি সেবা-এলাকা অনুপাত স্বয়ংক্রিয়ভাবে বেশি টেকসইতা বোঝায় না। প্রতিবেদিত এলাকায় ওভারল্যাপ থাকতে পারে এবং চাপযুক্ত অ্যাকুইফারে ভূগর্ভস্থ পানি-ভিত্তিক সেচ সম্পদচাপ বাড়াতে পারে।"))
    if view=="Research":
        with st.expander(L("Detailed BMDA table","বিস্তারিত BMDA সারণি")):
            d=bmda[bmda.upazila.isin(selected)][["upazila","fy","dtw_units","dtw_irrigated_area_ha","dtw_beneficiary_farmers","llp_units","llp_irrigated_area_ha","warpo_irrigable_area_ha","dtw_coverage_of_irrigable_area","ha_per_dtw","farmers_per_dtw","source"]].copy(); d.upazila=d.upazila.map(uname); d=d.rename(columns={"upazila":L("Upazila","উপজেলা"),"fy":L("Fiscal year","অর্থবছর"),"dtw_units":L("DTW units","DTW ইউনিট"),"dtw_irrigated_area_ha":L("Reported DTW service area (ha)","প্রতিবেদিত DTW সেবা এলাকা (হা)"),"dtw_beneficiary_farmers":L("Reported beneficiary farmers","প্রতিবেদিত উপকারভোগী কৃষক"),"llp_units":L("LLP units","LLP ইউনিট"),"llp_irrigated_area_ha":L("Reported LLP service area (ha)","প্রতিবেদিত LLP সেবা এলাকা (হা)"),"warpo_irrigable_area_ha":L("Irrigable-area baseline (ha)","সেচযোগ্য-এলাকা ভিত্তি (হা)"),"dtw_coverage_of_irrigable_area":L("DTW service-area ratio","DTW সেবা-এলাকা অনুপাত"),"ha_per_dtw":L("Reported hectares per DTW","প্রতি DTW প্রতিবেদিত হেক্টর"),"farmers_per_dtw":L("Reported farmers per DTW","প্রতি DTW প্রতিবেদিত কৃষক"),"source":L("Source","উৎস")}); st.dataframe(d.round(3),hide_index=True,use_container_width=True)
    st.markdown(f"#### {L('BBS productivity context — district only','BBS উৎপাদনশীলতা প্রেক্ষাপট — শুধু জেলা')}"); st.warning(L("BBS crop statistics here describe Naogaon district, not Mahadebpur or Sapahar individually.","এখানকার BBS ফসল পরিসংখ্যান নওগাঁ জেলার; মহাদেবপুর বা সাপাহারের পৃথক ফলাফল নয়।"))
    d=bbs[["crop","2023-24_area_ha","2023-24_yield_t_per_ha","2023-24_production_t","2024-25_area_ha","2024-25_yield_t_per_ha","2024-25_production_t","yield_change","production_change","geographic_level"]].copy(); d=d.rename(columns={"crop":L("Crop","ফসল"),"2023-24_area_ha":L("Area 2023–24 (ha)","এলাকা ২০২৩–২৪ (হা)"),"2023-24_yield_t_per_ha":L("Yield 2023–24 (t/ha)","ফলন ২০২৩–২৪ (টন/হা)"),"2023-24_production_t":L("Production 2023–24 (t)","উৎপাদন ২০২৩–২৪ (টন)"),"2024-25_area_ha":L("Area 2024–25 (ha)","এলাকা ২০২৪–২৫ (হা)"),"2024-25_yield_t_per_ha":L("Yield 2024–25 (t/ha)","ফলন ২০২৪–২৫ (টন/হা)"),"2024-25_production_t":L("Production 2024–25 (t)","উৎপাদন ২০২৪–২৫ (টন)"),"yield_change":L("Yield change","ফলন পরিবর্তন"),"production_change":L("Production change","উৎপাদন পরিবর্তন"),"geographic_level":L("Geographic level","ভৌগোলিক স্তর")}); st.dataframe(d.round(3),hide_index=True,use_container_width=True); source("Bangladesh Bureau of Statistics")

# ---------------- WATER STRESS ----------------
with tabs[3]:
    st.subheader(L("Water stress and groundwater pressure (E)","পানির চাপ ও ভূগর্ভস্থ পানির চাপ (E)")); st.warning(L("Groundwater-depth and stress evidence here is historical/study-period evidence, not a live 2026 groundwater measurement.","এখানকার ভূগর্ভস্থ পানির গভীরতা ও চাপের প্রমাণ ঐতিহাসিক/গবেষণাকালীন; এটি ২০২৬ সালের লাইভ মাপ নয়।"))
    ws=warpo[warpo.upazila.isin(selected)].copy(); wc=st.columns(len(selected))
    for col,up in zip(wc,selected):
        with col:
            r=ws[ws.upazila.eq(up)].iloc[0]; card(uname(up),L(f"Groundwater depth range {r.gwt_min_depth_m:.1f}–{r.gwt_max_depth_m:.1f} m. Very-high/high-stress unions: {int(r.very_high_stress_unions)}/{int(r.high)}. PRA scarcity: {r.pra_scarcity}.",f"ভূগর্ভস্থ পানির গভীরতা {r.gwt_min_depth_m:.1f}–{r.gwt_max_depth_m:.1f} মি। অতি-উচ্চ/উচ্চ-চাপ ইউনিয়ন: {int(r.very_high_stress_unions)}/{int(r.high)}। PRA ঘাটতি: {r.pra_scarcity}।"),"💧",[(L("Historical/study-period","ঐতিহাসিক/গবেষণাকালীন"),"yellow")])
    sl=ws[["upazila","very_high_stress_unions","high","moderate","low","very_low"]].melt(id_vars="upazila",var_name="class",value_name="unions"); names={"very_high_stress_unions":L("Very high","অতি উচ্চ"),"high":L("High","উচ্চ"),"moderate":L("Moderate","মাঝারি"),"low":L("Low","নিম্ন"),"very_low":L("Very low","অতি নিম্ন")}; sl["class"]=sl["class"].map(names); sl["Upazila_display"]=sl.upazila.map(uname); smap={L("Very high","অতি উচ্চ"):"#dc2626",L("High","উচ্চ"):"#ea580c",L("Moderate","মাঝারি"):"#ca8a04",L("Low","নিম্ন"):"#22c55e",L("Very low","অতি নিম্ন"):"#15803d"}
    fg=px.bar(sl,x="Upazila_display",y="unions",color="class",barmode="stack",color_discrete_map=smap,labels={"Upazila_display":L("Upazila","উপজেলা"),"unions":L("Number of unions","ইউনিয়নের সংখ্যা"),"class":L("Official stress class","সরকারি চাপ শ্রেণি")},title=L("Official IWM water-stress category counts","সরকারি IWM পানি-চাপ শ্রেণির ইউনিয়ন সংখ্যা")); st.plotly_chart(figstyle(fg,470),use_container_width=True); source("IWM High Barind water-stress assessment")
    rows=[]
    for _,r in ws.iterrows(): rows += [{"upazila":r.upazila,"year":"2021","value":r.water_use_2021_mcm,"type":L("Water use","পানি ব্যবহার")},{"upazila":r.upazila,"year":"2030","value":r.demand_2030_mcm,"type":L("Projected demand","প্রক্ষেপিত চাহিদা")},{"upazila":r.upazila,"year":"2041","value":r.demand_2041_mcm,"type":L("Projected demand","প্রক্ষেপিত চাহিদা")}]
    dd=pd.DataFrame(rows); dd["Upazila_display"]=dd.upazila.map(uname); fg=px.line(dd,x="year",y="value",color="Upazila_display",symbol="type",markers=True,color_discrete_map=COLORS,labels={"year":L("Reference / projection year","ভিত্তি / প্রক্ষেপণ বছর"),"value":L("Water use / demand (MCM)","পানি ব্যবহার / চাহিদা (MCM)"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Water-use baseline and projected demand","পানি ব্যবহারের ভিত্তি ও প্রক্ষেপিত চাহিদা")); st.plotly_chart(figstyle(fg),use_container_width=True); source("WARPO/IWM PRA baseline")
    if view=="Research":
        d=ws[["upazila","derived_ordinal_stress_score_0-100"]].copy(); d["Upazila_display"]=d.upazila.map(uname); fg=px.bar(d,x="Upazila_display",y="derived_ordinal_stress_score_0-100",color="Upazila_display",color_discrete_map=COLORS,labels={"Upazila_display":L("Upazila","উপজেলা"),"derived_ordinal_stress_score_0-100":L("Derived stress score (0–100)","ডেরাইভড স্ট্রেস স্কোর (০–১০০)")},title=L("Illustrative derived comparison — not official WSI","উদাহরণমূলক ডেরাইভড তুলনা — সরকারি WSI নয়")); st.plotly_chart(figstyle(fg,390),use_container_width=True)
    with st.expander(L("Official IWM WSI classification","সরকারি IWM WSI শ্রেণিবিন্যাস")):
        st.markdown(L("Official study thresholds: Very High >160; High 140–160; Moderate 120–140; Low 100–120; Very Low <100. This dashboard shows official category counts where available; it does not reconstruct union-level official WSI.","সরকারি গবেষণা সীমা: অতি উচ্চ >১৬০; উচ্চ ১৪০–১৬০; মাঝারি ১২০–১৪০; নিম্ন ১০০–১২০; অতি নিম্ন <১০০। ড্যাশবোর্ড সরকারি শ্রেণির সংখ্যা দেখায়; ইউনিয়ন-স্তরের সরকারি WSI পুনর্গঠন করে না।"))

# ---------------- RESILIENCE ----------------
with tabs[4]:
    st.subheader(L("Exploratory climate-resilience diagnostics (R)","অনুসন্ধানমূলক জলবায়ু-সহনশীলতা নির্ণায়ক (R)")); st.caption(L("Associations around unusually dry months; not a causal irrigation-effect estimate.","অস্বাভাবিক শুষ্ক মাসের আশপাশের সম্পর্ক; কারণগত সেচ-প্রভাব অনুমান নয়।"))
    a,bx,c=st.columns(3)
    with a: thr=st.slider(L("Dry-shock threshold: rainfall z ≤","শুষ্ক-ধাক্কা সীমা: বৃষ্টির z ≤"),-2.0,-.5,-1.0,.1,key="thr")
    with bx: lag=st.selectbox(L("Vegetation response lag","উদ্ভিদ প্রতিক্রিয়ার বিলম্ব"),[0,1,2,3],format_func=lambda k:L("Same month","একই মাস") if k==0 else L(f"+{k} month",f"+{k} মাস"),index=1,key="lag")
    with c: dur=st.selectbox(L("Dry-shock duration","শুষ্ক-ধাক্কার স্থায়িত্ব"),["any","single","two","three"],format_func=lambda k:{"any":L("Any dry-shock month","যেকোনো শুষ্ক-ধাক্কা মাস"),"single":L("Single-month shocks","এক-মাসের ধাক্কা"),"two":L("Exactly 2 consecutive months","ঠিক ২টি ধারাবাহিক মাস"),"three":L("3+ consecutive months","৩+ ধারাবাহিক মাস")}[k],key="dur")
    ridx=st.radio(L("Vegetation response indicator","উদ্ভিদ প্রতিক্রিয়া সূচক"),["NDVI","EVI"],horizontal=True,key="ridx"); pre="ndvi" if ridx=="NDVI" else "evi"; rz=f"{pre}_z_lag{lag}"; rv=f"{pre}_value_lag{lag}"
    full=add_runs(panel,thr); rf=full[full.upazila.isin(selected)&full.year.between(*years)&full.month.isin(months)].copy(); rf=tqfilter(rf,qmode,lag).dropna(subset=["rain_z",rz]); rf["sel_shock"]=duration_mask(rf,dur); rf["type"]=np.where(rf.sel_shock,L("Selected dry-shock months","নির্বাচিত শুষ্ক-ধাক্কা মাস"),L("Other eligible months","অন্যান্য উপযুক্ত মাস"))
    if rf.empty: st.warning(L("No observations remain for these settings.","এই সেটিংসে কোনো পর্যবেক্ষণ নেই।"))
    else:
        mcols=st.columns(len(selected))
        for col,up in zip(mcols,selected):
            with col:
                g=rf[rf.upazila.eq(up)]; sh=g[g.sel_shock]; oth=g[~g.sel_shock]; st.markdown(f"**📍 {uname(up)}**"); x,y,z=st.columns(3); x.metric(L("Selected shocks","নির্বাচিত ধাক্কা"),len(sh)); y.metric(L(f"Mean {ridx} response (z)",f"গড় {ridx} প্রতিক্রিয়া (z)"),n(sh[rz].mean(),2)); z.metric(L("Shock minus other","ধাক্কা বিয়োগ অন্যান্য"),n(sh[rz].mean()-oth[rz].mean(),2))
        r1,r2=st.columns(2)
        with r1:
            cp=rf.groupby(["upazila","type"],as_index=False)[rz].mean(); cp["Upazila_display"]=cp.upazila.map(uname); fg=px.bar(cp,x="Upazila_display",y=rz,color="type",barmode="group",color_discrete_map={L("Selected dry-shock months","নির্বাচিত শুষ্ক-ধাক্কা মাস"):"#dc2626",L("Other eligible months","অন্যান্য উপযুক্ত মাস"):"#64748b"},labels={"Upazila_display":L("Upazila","উপজেলা"),rz:L(f"Mean {ridx} anomaly at selected lag",f"নির্বাচিত বিলম্বে গড় {ridx} বিচ্যুতি")},title=L("Vegetation response in selected dry shocks","নির্বাচিত শুষ্ক ধাক্কায় উদ্ভিদ প্রতিক্রিয়া")); st.plotly_chart(figstyle(fg),use_container_width=True)
        with r2:
            dp=place(rf); dp["Quality"]=dp[f"target_quality_lag{lag}"].map(qname); fg=px.scatter(dp,x="rain_z",y=rz,color="Upazila_display",symbol="sel_shock",opacity=.7,color_discrete_map=COLORS,hover_data={"date":True,"rainfall_mm":":.1f",rv:":.3f",f"target_cov_lag{lag}":":.1%","Quality":True,"shock_len":True},labels={"rain_z":L("Rainfall anomaly at shock month (z)","ধাক্কার মাসে বৃষ্টির বিচ্যুতি (z)"),rz:L(f"{ridx} anomaly at +{lag} month(s)",f"+{lag} মাসে {ridx} বিচ্যুতি"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Rainfall shock vs lagged vegetation response","বৃষ্টির ধাক্কা বনাম বিলম্বিত উদ্ভিদ প্রতিক্রিয়া")); fg.add_vline(x=thr,line_dash="dash",line_color="#dc2626"); st.plotly_chart(figstyle(fg),use_container_width=True)
        source("CHIRPS v3 + MODIS MOD13Q1")
        st.markdown(f"#### {L('Lag comparison','বিলম্ব তুলনা')}"); rows=[]; base=full[full.upazila.isin(selected)&full.year.between(*years)&full.month.isin(months)].copy()
        for k in range(4):
            zc=f"{pre}_z_lag{k}"; tmp=tqfilter(base,qmode,k).dropna(subset=[zc]); tmp=tmp[duration_mask(tmp,dur)]
            for up,g in tmp.groupby("upazila"): rows.append({"upazila":up,"lag":k,"response":g[zc].mean(),"n":len(g)})
        ld=pd.DataFrame(rows)
        if not ld.empty:
            ld["Upazila_display"]=ld.upazila.map(uname); ld["lag_label"]=ld.lag.map(lambda k:L("Same month","একই মাস") if k==0 else L(f"+{k} month",f"+{k} মাস")); fg=px.line(ld,x="lag_label",y="response",color="Upazila_display",markers=True,color_discrete_map=COLORS,labels={"lag_label":L("Response lag","প্রতিক্রিয়া বিলম্ব"),"response":L(f"Mean {ridx} anomaly in selected shocks",f"নির্বাচিত ধাক্কায় গড় {ridx} বিচ্যুতি"),"Upazila_display":L("Upazila","উপজেলা")},title=L("Mean vegetation response across 0–3 month lags","০–৩ মাস বিলম্বে গড় উদ্ভিদ প্রতিক্রিয়া")); st.plotly_chart(figstyle(fg),use_container_width=True)
        st.info(L("BMDA technology data cover only a few fiscal years, so V1.0 does not present a causal Technology × Climate Shock coefficient. A defensible causal model needs aligned intervention/exposure, yield, groundwater and farmer-cost data.","BMDA প্রযুক্তি ডেটা অল্প কয়েকটি অর্থবছর কভার করে, তাই V1.0 কারণগত Technology × Climate Shock সহগ দেখায় না। বিশ্বাসযোগ্য কারণগত মডেলের জন্য সামঞ্জস্যকৃত হস্তক্ষেপ/এক্সপোজার, ফলন, ভূগর্ভস্থ পানি ও কৃষক-ব্যয় ডেটা দরকার।"))
# Extra research-only recovery diagnostic, kept separate from causal claims.
def recovery_table(df,thr,selected,years,months):
    s=add_runs(df,thr); rows=[]
    for up,g in s.groupby("upazila"):
        if up not in selected: continue
        g=g.sort_values("date_dt").reset_index(drop=True)
        for i in g.index[g.shock_start]:
            r=g.loc[i]
            if not(years[0]<=int(r.year)<=years[1] and int(r.month) in months): continue
            run=int(r.shock_len); end=min(i+run-1,len(g)-1); resp=g.loc[i:min(end+2,len(g)-1),["date_dt","ndvi_z"]].dropna()
            if resp.empty: continue
            j=resp.ndvi_z.idxmin(); minz=float(g.loc[j,"ndvi_z"]); mind=pd.Timestamp(g.loc[j,"date_dt"]); rec=np.nan; status=L("No material decline by rule","নিয়মে উল্লেখযোগ্য পতন নেই")
            if minz<-.25:
                status=L("Not recovered within 6 months","৬ মাসে পুনরুদ্ধার নয়"); after=g[(g.date_dt>mind)&(g.date_dt<=mind+pd.DateOffset(months=6))&g.ndvi_z.ge(-.25)]
                if not after.empty:
                    rd=pd.Timestamp(after.iloc[0].date_dt); rec=(rd.year-mind.year)*12+(rd.month-mind.month); status=L("Recovered by dashboard rule","ড্যাশবোর্ড নিয়মে পুনরুদ্ধার")
            rows.append({L("Upazila","উপজেলা"):uname(up),L("Shock start","ধাক্কা শুরু"):pd.Timestamp(r.date_dt).strftime("%Y-%m"),L("Shock duration (months)","ধাক্তার সময়কাল (মাস)"):run,L("Mean rainfall anomaly during run (z)","ধাক্কায় গড় বৃষ্টি বিচ্যুতি (z)"):g.loc[i:end,"rain_z"].mean(),L("Minimum NDVI anomaly (run + 2m)","সর্বনিম্ন NDVI বিচ্যুতি (ধাক্কা + ২মাস)"):minz,L("Months to return ≥ -0.25 SD","≥ -০.২৫ SD-তে ফিরতে মাস"):rec,L("Recovery status","পুনরুদ্ধার অবস্থা"):status})
    return pd.DataFrame(rows)
if view=="Research":
    with tabs[4]:
        with st.expander(L("Exploratory recovery diagnostic","অনুসন্ধানমূলক পুনরুদ্ধার নির্ণায়ক")):
            rt=recovery_table(panel,thr,selected,years,months)
            if rt.empty: st.info(L("No shock runs available under the selected filters.","নির্বাচিত ফিল্টারে কোনো শুষ্ক-ধাক্কা ধারা নেই।"))
            else: st.dataframe(rt.round(3),hide_index=True,use_container_width=True)
            st.caption(L("Transparent rule: a material decline is NDVI anomaly < -0.25 SD; recovery is the first later month within six months with NDVI anomaly ≥ -0.25 SD. This is an exploratory dashboard definition, not an agronomic standard.","স্বচ্ছ নিয়ম: NDVI বিচ্যুতি < -০.২৫ SD হলে উল্লেখযোগ্য পতন; এরপর ৬ মাসের মধ্যে প্রথমবার NDVI ≥ -০.২৫ SD হলে পুনরুদ্ধার। এটি অনুসন্ধানমূলক ড্যাশবোর্ড সংজ্ঞা, কৃষিবৈজ্ঞানিক মানদণ্ড নয়।"))

# ---------------- ACTIONS ----------------
def action(title,area,priority,tone,why,what,actors,time,rtype,evidence,preq,trade,monitor,impact,src):
    st.markdown(f'''<div class="action action-{tone}"><div>{b(priority,tone)}{b(rtype,"blue")}{b(evidence,"purple")}</div><h3 style="margin:.4rem 0">{escape(title)}</h3><div class="grid"><div class="item"><b>📍 {escape(L("Where","কোথায়"))}:</b> {escape(area)}</div><div class="item"><b>👥 {escape(L("Potential lead / coordination","সম্ভাব্য নেতৃত্ব / সমন্বয়"))}:</b> {escape(actors)}</div><div class="item"><b>🧾 {escape(L("Why","কেন"))}:</b> {escape(why)}</div><div class="item"><b>⏱ {escape(L("Time horizon","সময়সীমা"))}:</b> {escape(time)}</div><div class="item"><b>🎯 {escape(L("What to do","কী করতে হবে"))}:</b> {escape(what)}</div><div class="item"><b>🛠 {escape(L("Prerequisite / feasibility","পূর্বশর্ত / বাস্তবায়ন"))}:</b> {escape(preq)}</div><div class="item"><b>⚖️ {escape(L("Trade-off","সম্ভাব্য ঝুঁকি/সমঝোতা"))}:</b> {escape(trade)}</div><div class="item"><b>📏 {escape(L("Monitor success with","সাফল্য মাপুন"))}:</b> {escape(monitor)}</div><div class="item"><b>⚙️🌾🛡️💧 {escape(L("T/P/R/E effect","T/P/R/E প্রভাব"))}:</b> {escape(impact)}</div><div class="item"><b>📚 {escape(L("Evidence source","প্রমাণের উৎস"))}:</b> {escape(src)}</div></div></div>''',unsafe_allow_html=True)

with tabs[5]:
    st.subheader(L("Evidence-informed recommended actions","প্রমাণভিত্তিক করণীয়")); st.caption(L("These are planning and prioritization recommendations. Groundwater restrictions, engineering works and crop interventions still require current site-specific technical and authority validation.","এগুলো পরিকল্পনা ও অগ্রাধিকার সুপারিশ। ভূগর্ভস্থ পানি সীমিতকরণ, প্রকৌশল কাজ ও ফসল হস্তক্ষেপের আগে বর্তমান সাইট-নির্দিষ্ট কারিগরি ও কর্তৃপক্ষের যাচাই দরকার।"))
    st.markdown(f'''<div class="flow"><div class="step">📊 {escape(L("Evidence","প্রমাণ"))}</div><div class="step">🔎 {escape(L("Diagnosis","রোগনির্ণয়"))}</div><div class="step">🚦 {escape(L("Priority","অগ্রাধিকার"))}</div><div class="step">🎯 {escape(L("Action","করণীয়"))}</div><div class="step">👥 {escape(L("Responsibility","দায়িত্ব"))}</div><div class="step">📏 {escape(L("Monitoring","পর্যবেক্ষণ"))}</div></div>''',unsafe_allow_html=True)
    wm=warpo.set_index("upazila")
    if "Sapahar" in selected:
        s=wm.loc["Sapahar"]; st.markdown(f"### 🔴 {L('Sapahar — high-priority groundwater-management area','সাপাহার — উচ্চ-অগ্রাধিকার ভূগর্ভস্থ পানি ব্যবস্থাপনা এলাকা')}")
        action(L("Control additional groundwater abstraction in the highest-stress areas","সর্বোচ্চ চাপযুক্ত এলাকায় অতিরিক্ত ভূগর্ভস্থ পানি উত্তোলন নিয়ন্ত্রণ করুন"),L("Sapahar, especially very-high/high-stress unions","সাপাহার, বিশেষত অতি-উচ্চ/উচ্চ-চাপ ইউনিয়ন"),L("Urgent","জরুরি"),"red",L(f"Study-period evidence identifies {int(s.very_high_stress_unions)} very-high-stress unions and {int(s.high)} high-stress union; historical GWT reaches {s.gwt_max_depth_m:.1f} m.",f"গবেষণাকালীন প্রমাণে {int(s.very_high_stress_unions)}টি অতি-উচ্চ-চাপ ও {int(s.high)}টি উচ্চ-চাপ ইউনিয়ন; ঐতিহাসিক GWT {s.gwt_max_depth_m:.1f} মি পর্যন্ত।"),L("Require water-resource assessment before major new abstraction; prioritize efficiency and alternative water sources first.","বড় নতুন উত্তোলনের আগে পানি-সম্পদ মূল্যায়ন; আগে দক্ষতা ও বিকল্প পানির উৎসকে অগ্রাধিকার।"),L("BMDA, WARPO and relevant local/regulatory authorities","BMDA, WARPO ও সংশ্লিষ্ট স্থানীয়/নিয়ন্ত্রক কর্তৃপক্ষ"),L("Immediate–2 years","তাৎক্ষণিক–২ বছর"),L("Official-source recommendation","সরকারি উৎসের সুপারিশ"),L("Strong in cited historical/study-period evidence","উদ্ধৃত ঐতিহাসিক/গবেষণাকালীন প্রমাণে শক্তিশালী"),L("Refresh union-level groundwater status before enforcement.","প্রয়োগের আগে ইউনিয়ন-স্তরের বর্তমান ভূগর্ভস্থ পানি অবস্থা হালনাগাদ করুন।"),L("Restriction without replacement water can reduce farmer irrigation access.","বিকল্প পানি ছাড়া সীমাবদ্ধতা কৃষকের সেচ-প্রবেশ কমাতে পারে।"),L("Monthly GWT, new wells, pump hours/abstraction proxy, irrigated area and crop outcomes.","মাসিক GWT, নতুন কূপ, পাম্পঘণ্টা/উত্তোলন প্রক্সি, সেচকৃত এলাকা ও ফসল ফলাফল।"),L("T redirect · P protect · R strengthen · E reduce","T পুনর্নির্দেশ · P সুরক্ষা · R শক্তিশালী · E হ্রাস"),"WARPO/IWM PRA baseline + IWM High Barind assessment")
        action(L("Restore surface-water storage and expand conjunctive use","পৃষ্ঠজল সংরক্ষণ পুনরুদ্ধার ও সমন্বিত ব্যবহার বাড়ান"),L("Sapahar; suitable beels/ponds after feasibility assessment","সাপাহার; সম্ভাব্যতা যাচাইয়ের পর উপযুক্ত বিল/পুকুর"),L("High priority","উচ্চ অগ্রাধিকার"),"orange",L("Official studies recommend reducing groundwater dependence and identify Sapahar beels for retention/re-excavation.","সরকারি গবেষণায় ভূগর্ভস্থ পানির নির্ভরতা কমাতে ও সাপাহারের বিল পুনঃখনন/ধারণক্ষমতা বাড়াতে বলা হয়েছে।"),L("Assess and phase restoration of identified water bodies; examples in the studies include Damudahar, Dak, Kayamar, Baksha, Puroil, Mahil, Jaba and a Jobai Beel pilot; connect stored monsoon water to irrigation where technically viable.","চিহ্নিত জলাশয় ধাপে পুনরুদ্ধার করুন; গবেষণায় Damudahar, Dak, Kayamar, Baksha, Puroil, Mahil, Jaba এবং Jobai Beel পাইলটের উল্লেখ আছে; কারিগরিভাবে সম্ভব হলে সংরক্ষিত মৌসুমি পানি সেচে যুক্ত করুন।"),L("BMDA, water-resource agencies, local government and communities","BMDA, পানি-সম্পদ সংস্থা, স্থানীয় সরকার ও জনগোষ্ঠী"),L("1–5 years, phased","১–৫ বছর, পর্যায়ক্রমে"),L("Official-source recommendation","সরকারি উৎসের সুপারিশ"),L("Strong direction; site feasibility required","দিকনির্দেশে শক্তিশালী; সাইট-সম্ভাব্যতা দরকার"),L("Engineering, land, sediment, drainage and water-quality assessment first.","আগে প্রকৌশল, ভূমি, পলি, নিষ্কাশন ও পানির মান মূল্যায়ন।"),L("Poor design may create drainage/waterlogging or maintenance problems.","খারাপ নকশা জলাবদ্ধতা/নিষ্কাশন বা রক্ষণাবেক্ষণ সমস্যা তৈরি করতে পারে।"),L("Storage volume, surface-water irrigation share, groundwater abstraction proxy and dry-season GWT.","ধারণক্ষমতা, পৃষ্ঠজল-সেচের অংশ, ভূগর্ভস্থ উত্তোলন প্রক্সি ও শুষ্ক-মৌসুম GWT।"),L("T diversify · P support · R strengthen · E reduce","T বৈচিত্র্য · P সহায়তা · R শক্তিশালী · E হ্রাস"),"WARPO/IWM PRA + IWM High Barind recommendations")
        action(L("Improve irrigation efficiency before expanding groundwater capacity","ভূগর্ভস্থ সক্ষমতা বাড়ানোর আগে সেচ দক্ষতা উন্নত করুন"),L("Sapahar, especially stressed irrigation areas","সাপাহার, বিশেষত চাপযুক্ত সেচ এলাকা"),L("High priority","উচ্চ অগ্রাধিকার"),"orange",L("High groundwater stress means production should be pursued with less abstraction wherever feasible.","উচ্চ ভূগর্ভস্থ পানি-চাপের কারণে সম্ভব হলে কম উত্তোলনে উৎপাদন লক্ষ্য অর্জন করা উচিত।"),L("Improve scheduling, reduce conveyance losses, monitor pump use and apply water-saving methods such as AWD where crop-wise and technically appropriate.","সেচ সময়সূচি উন্নত, পরিবহন ক্ষতি কমানো, পাম্প ব্যবহার পর্যবেক্ষণ এবং ফসল/কারিগরি উপযোগিতা অনুযায়ী AWD-এর মতো পদ্ধতি।"),L("BMDA, DAE, irrigation managers and farmer groups","BMDA, DAE, সেচ ব্যবস্থাপক ও কৃষকগোষ্ঠী"),L("0–3 years","০–৩ বছর"),L("Evidence-informed dashboard recommendation","ড্যাশবোর্ডের প্রমাণভিত্তিক সুপারিশ"),L("Moderate–strong direction; local water-use data missing","দিকনির্দেশে মাঝারি–শক্তিশালী; স্থানীয় পানি-ব্যবহার ডেটা অনুপস্থিত"),L("Field assessment of irrigation systems and crop calendars.","সেচ ব্যবস্থা ও ফসল ক্যালেন্ডারের মাঠ-সমীক্ষা।"),L("Efficiency can trigger irrigated-area expansion if abstraction is not monitored.","উত্তোলন পর্যবেক্ষণ না করলে দক্ষতা বৃদ্ধিতে সেচ এলাকা বাড়তে পারে।"),L("Water/ha or energy/ha, pump hours, area, yield and GWT.","পানি/হা বা শক্তি/হা, পাম্পঘণ্টা, এলাকা, ফলন ও GWT।"),L("T improve · P maintain · R strengthen · E reduce","T উন্নত · P বজায় · R শক্তিশালী · E হ্রাস"),"IWM/WARPO direction + dashboard synthesis")
        action(L("Promote lower-water-demand crop diversification in severe-stress dry-season areas","তীব্র চাপের শুষ্ক-মৌসুম এলাকায় কম পানি-চাহিদার ফসল বৈচিত্র্য উৎসাহিত করুন"),L("Selected high-stress parts of Sapahar","সাপাহারের নির্বাচিত উচ্চ-চাপ অংশ"),L("High priority","উচ্চ অগ্রাধিকার"),"orange",L("WARPO/IWM recommends lower-water-requirement crops instead of excessive dependence on HYV Boro in stressed areas.","WARPO/IWM চাপযুক্ত এলাকায় HYV বোরোর অতিরিক্ত নির্ভরতার বদলে কম পানি-চাহিদার ফসলের সুপারিশ করে।"),L("Pilot farmer- and market-informed alternatives; do not impose a blanket Boro ban.","কৃষক ও বাজারভিত্তিক বিকল্প পাইলট করুন; সর্বজনীন বোরো নিষেধাজ্ঞা নয়।"),L("DAE, farmers, BMDA and market/value-chain actors","DAE, কৃষক, BMDA ও বাজার/ভ্যালু-চেইন সংশ্লিষ্টরা"),L("1–4 years; pilots first","১–৪ বছর; আগে পাইলট"),L("Official-source recommendation","সরকারি উৎসের সুপারিশ"),L("Strong direction; crop economics still needed","দিকনির্দেশে শক্তিশালী; ফসলভিত্তিক অর্থনীতি দরকার"),L("Crop suitability, market, irrigation and income assessment.","ফসল উপযোগিতা, বাজার, সেচ ও আয় মূল্যায়ন।"),L("Lower water demand can still reduce income if markets or yields are unfavorable.","বাজার/ফলন অনুকূল না হলে কম পানি-চাহিদার ফসল আয় কমাতে পারে।"),L("Crop mix, water/ha, gross margin, yield, adoption and GWT.","ফসল মিশ্রণ, পানি/হা, গ্রস মার্জিন, ফলন, গ্রহণ ও GWT।"),L("T adapt · P protect · R diversify · E reduce","T অভিযোজন · P সুরক্ষা · R বৈচিত্র্য · E হ্রাস"),"WARPO/IWM PRA recommendations")
        action(L("Establish union-level groundwater and abstraction monitoring","ইউনিয়ন-স্তরে ভূগর্ভস্থ পানি ও উত্তোলন পর্যবেক্ষণ চালু করুন"),L("Sapahar","সাপাহার"),L("Urgent evidence need","জরুরি প্রমাণের প্রয়োজন"),"blue",L("The strongest groundwater evidence is historical/study-period; current status cannot be confirmed from CHIRPS/MODIS.","সবচেয়ে শক্তিশালী ভূগর্ভস্থ পানি প্রমাণ ঐতিহাসিক/গবেষণাকালীন; CHIRPS/MODIS থেকে বর্তমান অবস্থা নিশ্চিত করা যায় না।"),L("Measure GWT monthly; record new wells, pump hours/energy, irrigation source and crop/area served.","মাসিক GWT মাপুন; নতুন কূপ, পাম্পঘণ্টা/শক্তি, সেচ উৎস ও সেবা পাওয়া ফসল/এলাকা রেকর্ড করুন।"),L("WARPO/BMDA with local monitoring partners","WARPO/BMDA ও স্থানীয় পর্যবেক্ষণ অংশীদার"),L("Start immediately; routine thereafter","তাৎক্ষণিক শুরু; এরপর নিয়মিত"),L("Evidence-informed dashboard recommendation","ড্যাশবোর্ডের প্রমাণভিত্তিক সুপারিশ"),L("Strong need due to data-age gap","ডেটার সময়গত ঘাটতির কারণে শক্তিশালী প্রয়োজন"),L("Consistent monitoring protocol and station IDs.","সামঞ্জস্যপূর্ণ পর্যবেক্ষণ প্রোটোকল ও স্টেশন আইডি।"),L("Recurring monitoring cost, but lower risk of decisions from stale data.","নিয়মিত পর্যবেক্ষণ ব্যয় আছে, তবে পুরোনো ডেটার সিদ্ধান্তঝুঁকি কমে।"),L("GWT trend, abstraction proxy, well count, source share and seasonal recovery.","GWT প্রবণতা, উত্তোলন প্রক্সি, কূপ সংখ্যা, উৎসের অংশ ও মৌসুমি পুনরুদ্ধার।"),L("T measure · P enable evaluation · R track · E monitor","T পরিমাপ · P মূল্যায়ন · R ট্র্যাক · E পর্যবেক্ষণ"),"Dashboard evidence-gap assessment + WARPO/IWM variables")
    if "Mahadebpur" in selected:
        m=wm.loc["Mahadebpur"]; st.markdown(f"### 🟡 {L('Mahadebpur — preventive management area','মহাদেবপুর — প্রতিরোধমূলক ব্যবস্থাপনা এলাকা')}")
        action(L("Monitor the high-stress pocket and avoid unnecessary groundwater expansion","উচ্চ-চাপ অংশ পর্যবেক্ষণ করুন এবং অপ্রয়োজনীয় ভূগর্ভস্থ পানি সম্প্রসারণ এড়ান"),L("Mahadebpur; target the high-stress pocket identified by the study","মহাদেবপুর; গবেষণায় চিহ্নিত উচ্চ-চাপ অংশে লক্ষ্য"),L("Preventive","প্রতিরোধমূলক"),"yellow",L(f"Baseline evidence records {int(m.high)} high-stress union, no very-high-stress unions and historical max GWT of {m.gwt_max_depth_m:.1f} m.",f"ভিত্তিতে {int(m.high)}টি উচ্চ-চাপ ইউনিয়ন, কোনো অতি-উচ্চ-চাপ ইউনিয়ন নেই এবং ঐতিহাসিক সর্বোচ্চ GWT {m.gwt_max_depth_m:.1f} মি।"),L("Refresh monitoring and improve efficiency before new groundwater capacity; do not automatically apply Sapahar-level blanket restrictions.","নতুন ভূগর্ভস্থ সক্ষমতার আগে পর্যবেক্ষণ হালনাগাদ ও দক্ষতা উন্নত করুন; সাপাহার-স্তরের সর্বজনীন সীমাবদ্ধতা স্বয়ংক্রিয়ভাবে প্রয়োগ করবেন না।"),L("BMDA, WARPO and local irrigation management","BMDA, WARPO ও স্থানীয় সেচ ব্যবস্থাপনা"),L("0–3 years","০–৩ বছর"),L("Evidence-informed dashboard recommendation","ড্যাশবোর্ডের প্রমাণভিত্তিক সুপারিশ"),L("Moderate; historical baseline needs refresh","মাঝারি; ঐতিহাসিক ভিত্তি হালনাগাদ দরকার"),L("Current union-level GWT measurements.","বর্তমান ইউনিয়ন-স্তরের GWT মাপ।"),L("Over-restriction could unnecessarily constrain irrigation where conditions are better.","অতিরিক্ত সীমাবদ্ধতা তুলনামূলক ভালো এলাকায় অপ্রয়োজনীয়ভাবে সেচ সীমিত করতে পারে।"),L("Monthly GWT, new DTWs, pump use, irrigation service and crop outcomes.","মাসিক GWT, নতুন DTW, পাম্প ব্যবহার, সেচ সেবা ও ফসল ফলাফল।"),L("T optimize · P maintain · R protect · E prevent deterioration","T অপ্টিমাইজ · P বজায় · R সুরক্ষা · E অবনতি প্রতিরোধ"),"IWM stress evidence + WARPO/IWM baseline + dashboard synthesis")
        action(L("Improve irrigation efficiency and diversify water sources before expansion","সম্প্রসারণের আগে সেচ দক্ষতা ও পানির উৎস বৈচিত্র্য করুন"),L("Mahadebpur","মহাদেবপুর"),L("Preventive / high value","প্রতিরোধমূলক / উচ্চ মূল্য"),"yellow",L("Mahadebpur has substantial recorded DTW infrastructure; the preventive objective is to preserve productivity while avoiding future groundwater deterioration.","মহাদেবপুরে উল্লেখযোগ্য DTW অবকাঠামো আছে; লক্ষ্য হলো উৎপাদনশীলতা বজায় রেখে ভবিষ্যৎ ভূগর্ভস্থ পানি অবনতি ঠেকানো।"),L("Audit utilization/service overlap, reduce losses, improve scheduling and use surface water conjunctively where feasible.","ব্যবহার/সেবা ওভারল্যাপ অডিট, ক্ষতি কমানো, সময়সূচি উন্নত এবং সম্ভব হলে পৃষ্ঠজল সমন্বিত ব্যবহার।"),L("BMDA, DAE, irrigation managers and water-user groups","BMDA, DAE, সেচ ব্যবস্থাপক ও পানি-ব্যবহারকারী গোষ্ঠী"),L("0–4 years","০–৪ বছর"),L("Evidence-informed dashboard recommendation","ড্যাশবোর্ডের প্রমাণভিত্তিক সুপারিশ"),L("Moderate; direct water-use data missing","মাঝারি; সরাসরি পানি-ব্যবহার ডেটা অনুপস্থিত"),L("Field-level water-use and infrastructure assessment.","মাঠ-স্তরের পানি ব্যবহার ও অবকাঠামো মূল্যায়ন।"),L("Efficiency alone may not reduce total abstraction if irrigated area expands.","সেচ এলাকা বাড়লে শুধু দক্ষতা মোট উত্তোলন নাও কমাতে পারে।"),L("Water/ha or energy/ha, area, service overlap, yield and GWT.","পানি/হা বা শক্তি/হা, এলাকা, সেবা ওভারল্যাপ, ফলন ও GWT।"),L("T improve · P maintain · R protect · E stabilize","T উন্নত · P বজায় · R সুরক্ষা · E স্থিতিশীল"),"BMDA focal panel + WARPO/IWM direction")

    st.markdown(f"#### {L('Implementation pathway','বাস্তবায়ন পথ')}")
    if "Sapahar" in selected: st.markdown(L("**Sapahar:** refresh groundwater monitoring → control/assess new abstraction in highest-stress areas → expand surface-water retention → improve irrigation efficiency → pilot lower-water-demand crop diversification → monitor yield, income and groundwater outcomes.","**সাপাহার:** ভূগর্ভস্থ পানি পর্যবেক্ষণ হালনাগাদ → সর্বোচ্চ চাপ এলাকায় নতুন উত্তোলন মূল্যায়ন/নিয়ন্ত্রণ → পৃষ্ঠজল সংরক্ষণ বাড়ানো → সেচ দক্ষতা উন্নত → কম পানি-চাহিদার ফসল পাইলট → ফলন, আয় ও ভূগর্ভস্থ পানি পর্যবেক্ষণ।"))
    if "Mahadebpur" in selected: st.markdown(L("**Mahadebpur:** refresh monitoring → target the high-stress pocket → audit irrigation efficiency/utilization → diversify water sources where feasible → prevent unnecessary expansion while maintaining productivity.","**মহাদেবপুর:** পর্যবেক্ষণ হালনাগাদ → উচ্চ-চাপ অংশকে লক্ষ্য → সেচ দক্ষতা/ব্যবহার অডিট → সম্ভব হলে পানির উৎস বৈচিত্র্য → উৎপাদনশীলতা বজায় রেখে অপ্রয়োজনীয় সম্প্রসারণ ঠেকানো।"))
    d1,d2=st.columns(2)
    with d1: card(L("Do","যা করা উচিত"),L("Use current groundwater monitoring, efficiency-first irrigation, surface-water alternatives, targeted crop adaptation and explicit outcome monitoring.","বর্তমান ভূগর্ভস্থ পানি পর্যবেক্ষণ, দক্ষতা-প্রথম সেচ, পৃষ্ঠজল বিকল্প, লক্ষ্যভিত্তিক ফসল অভিযোজন ও ফলাফল পর্যবেক্ষণ ব্যবহার করুন।"),"✅",[(L("Evidence to action","প্রমাণ থেকে করণীয়"),"green")])
    with d2: card(L("Avoid","যা এড়ানো উচিত"),L("Do not treat more DTWs as automatically resilient; do not equate NDVI with yield, service area with unique irrigated land, historical groundwater evidence with live conditions, or correlation with causation.","আরও DTW-কে স্বয়ংক্রিয় সহনশীলতা ভাববেন না; NDVI=ফলন, সেবা এলাকা=স্বতন্ত্র সেচকৃত জমি, ঐতিহাসিক পানি=লাইভ অবস্থা, বা সহসম্পর্ক=কারণ ধরে নেবেন না।"),"⛔",[(L("Misinterpretation safeguard","ভুল ব্যাখ্যা প্রতিরোধ"),"red")])
    st.markdown(f"#### {L('Highest-priority data to collect next','পরবর্তী সর্বোচ্চ-অগ্রাধিকার ডেটা')}")
    gaps=pd.DataFrame([[L("Union-level groundwater depth","ইউনিয়ন-স্তরের ভূগর্ভস্থ পানির গভীরতা"),L("Monthly; pre/post irrigation season","মাসিক; সেচ মৌসুমের আগে/পরে"),L("Confirm whether historical stress is improving or worsening","ঐতিহাসিক চাপ উন্নত নাকি খারাপ হচ্ছে নিশ্চিত করা")],[L("Pump hours / electricity / abstraction proxy","পাম্পঘণ্টা / বিদ্যুৎ / উত্তোলন প্রক্সি"),L("Monthly/seasonal","মাসিক/মৌসুমি"),L("Measure actual technology pressure on groundwater","ভূগর্ভস্থ পানিতে প্রযুক্তির প্রকৃত চাপ মাপা")],[L("Crop-specific area, production and yield","ফসলভিত্তিক এলাকা, উৎপাদন ও ফলন"),L("Seasonal/annual","মৌসুমি/বার্ষিক"),L("Replace NDVI-only productivity proxy","শুধু NDVI-ভিত্তিক উৎপাদনশীলতা প্রক্সি প্রতিস্থাপন")],[L("Irrigation source and water use by crop","ফসলভিত্তিক সেচ উৎস ও পানি ব্যবহার"),L("Seasonal","মৌসুমি"),L("Link technology to water demand and resilience","প্রযুক্তিকে পানি-চাহিদা ও সহনশীলতার সাথে যুক্ত করা")],[L("Farm cost, price and income","খামার ব্যয়, মূল্য ও আয়"),L("Seasonal","মৌসুমি"),L("Evaluate welfare and crop-diversification trade-offs","কল্যাণ ও ফসল বৈচিত্র্যের সমঝোতা মূল্যায়ন")],[L("Intervention / treatment data","হস্তক্ষেপ / ট্রিটমেন্ট ডেটা"),L("Before and after pilot","পাইলটের আগে ও পরে"),L("Move toward causal evaluation","কারণগত মূল্যায়নের দিকে যাওয়া")]],columns=[L("Dataset","ডেটাসেট"),L("Suggested frequency","প্রস্তাবিত ঘনত্ব"),L("Why it matters","কেন দরকার")]); st.dataframe(gaps,hide_index=True,use_container_width=True)
# ---------------- DATA, METHODS & DOWNLOADS ----------------
with tabs[6]:
    st.subheader(L("Data, methods, uncertainty and downloads","ডেটা, পদ্ধতি, অনিশ্চয়তা ও ডাউনলোড"))
    st.markdown(f"#### {L('What we can say / what we cannot yet say','আমরা কী বলতে পারি / এখনো কী বলতে পারি না')}")
    a,bx=st.columns(2)
    with a: card(L("Supported by current evidence","বর্তমান প্রমাণে সমর্থিত"),L("Sapahar has historically/study-period been identified as substantially more groundwater-stressed than Mahadebpur; both have BMDA irrigation records; CHIRPS/MODIS provide a 2001–2025 climate/vegetation record; rainfall-shock associations can be described transparently.","সাপাহার ঐতিহাসিক/গবেষণাকালীনভাবে মহাদেবপুরের তুলনায় বেশি ভূগর্ভস্থ পানি-চাপযুক্ত; উভয় উপজেলায় BMDA সেচ রেকর্ড আছে; CHIRPS/MODIS ২০০১–২০২৫ জলবায়ু/উদ্ভিদ রেকর্ড দেয়; বৃষ্টির ধাক্কার সম্পর্ক স্বচ্ছভাবে বর্ণনা করা যায়।"),"✅",[(L("Evidence-supported","প্রমাণসমর্থিত"),"green")])
    with bx: card(L("Not established yet","এখনো প্রতিষ্ঠিত নয়"),L("The dashboard does not establish that BMDA irrigation caused NDVI changes, that NDVI equals crop yield, current groundwater level in every union, the optimal number of DTWs, the causal welfare effect of technology, or a numerical value for U=f(T,P,R,E).","ড্যাশবোর্ড প্রমাণ করে না যে BMDA সেচ NDVI পরিবর্তনের কারণ, NDVI-ই ফসল ফলন, প্রতিটি ইউনিয়নের বর্তমান পানিস্তর, DTW-এর সর্বোত্তম সংখ্যা, প্রযুক্তির কারণগত কল্যাণ প্রভাব, বা U=f(T,P,R,E)-এর সংখ্যামান।"),"⚠️",[(L("Evidence gap","প্রমাণের ঘাটতি"),"yellow")])

    st.markdown(f"#### {L('Source provenance','উৎস ও প্রোভেন্যান্স')}")
    prov=pd.DataFrame([["CHIRPS v3","UCSB Climate Hazards Center","2001–2025",L("Pentad precipitation → monthly upazila-polygon means","পেন্টাড বৃষ্টিপাত → মাসিক উপজেলা-পলিগন গড়"),L("Climate, anomalies, resilience","জলবায়ু, বিচ্যুতি, সহনশীলতা")],["MODIS MOD13Q1","NASA/USGS MODIS","2001–2025",L("16-day NDVI/EVI → valid-pixel-weighted monthly means; 7 missing months interpolated and flagged","১৬-দিনের NDVI/EVI → বৈধ-পিক্সেল-ওজনযুক্ত মাসিক গড়; ৭ মাস ইন্টারপোলেট ও ফ্ল্যাগ"),L("Vegetation proxy, resilience","উদ্ভিদ প্রক্সি, সহনশীলতা")],["BMDA Annual Reports","Barind Multipurpose Development Authority","2017–18 to 2020–21",L("Upazila DTW/LLP units and reported service areas","উপজেলা DTW/LLP ইউনিট ও প্রতিবেদিত সেবা এলাকা"),L("Technology","প্রযুক্তি")],["WARPO/IWM PRA baseline","WARPO / IWM-BCAS",L("Historical / study-period","ঐতিহাসিক / গবেষণাকালীন"),L("Groundwater depth, irrigable area, demand, scarcity","ভূগর্ভস্থ পানির গভীরতা, সেচযোগ্য এলাকা, চাহিদা, ঘাটতি"),L("Water stress / resource pressure","পানি-চাপ / সম্পদচাপ")],["IWM High Barind assessment","Institute of Water Modelling",L("Historical / study-period","ঐতিহাসিক / গবেষণাকালীন"),L("Official stress categories and recommendations","সরকারি চাপ শ্রেণি ও সুপারিশ"),L("Water stress / actions","পানি-চাপ / করণীয়")],["BBS crop statistics","Bangladesh Bureau of Statistics","2023–24, 2024–25",L("Naogaon district context only","শুধু নওগাঁ জেলা প্রেক্ষাপট"),L("Productivity context, not focal-upazila outcome","উৎপাদনশীলতা প্রেক্ষাপট, ফোকাল উপজেলা ফলাফল নয়")]],columns=[L("Dataset","ডেটাসেট"),L("Provider","প্রদানকারী"),L("Period","সময়কাল"),L("Transformation / use","রূপান্তর / ব্যবহার"),L("Role","ভূমিকা")]); st.dataframe(prov,hide_index=True,use_container_width=True)

    st.markdown(f"#### {L('Quality and interpolation','ডেটার মান ও ইন্টারপোলেশন')}"); q1,q2,q3=st.columns(3); q1.metric(L("Final monthly rows","চূড়ান্ত মাসিক সারি"),len(panel)); q2.metric(L("Interpolated MODIS months","ইন্টারপোলেটেড MODIS মাস"),int(panel.MODIS_source_status.eq("interpolated").sum())); q3.metric(L("Mean MODIS coverage proxy","গড় MODIS কভারেজ প্রক্সি"),f"{panel.MODIS_coverage_proxy.mean():.1%}")
    with st.expander(L("Interpolated months — human-readable audit","ইন্টারপোলেটেড মাস — সহজপাঠ্য অডিট"),expanded=(view=="Research")):
        d=interp.copy(); d.upazila=d.upazila.map(uname); d=d.rename(columns={"upazila":L("Upazila","উপজেলা"),"date":L("Missing month","অনুপস্থিত মাস"),"previous_observed_month":L("Previous observed month","পূর্ববর্তী পর্যবেক্ষিত মাস"),"next_observed_month":L("Next observed month","পরবর্তী পর্যবেক্ষিত মাস"),"interpolation_fraction":L("Interpolation fraction","ইন্টারপোলেশন ভগ্নাংশ"),"NDVI_interpolated":L("Interpolated NDVI","ইন্টারপোলেটেড NDVI"),"EVI_interpolated":L("Interpolated EVI","ইন্টারপোলেটেড EVI"),"raw_total_composites":L("Raw MODIS composites","মূল MODIS কম্পোজিট"),"raw_valid_composites":L("Valid MODIS composites","বৈধ MODIS কম্পোজিট"),"raw_total_valid_pixels":L("Valid pixels before interpolation","ইন্টারপোলেশনের আগে বৈধ পিক্সেল")}); keep=[L("Upazila","উপজেলা"),L("Missing month","অনুপস্থিত মাস"),L("Previous observed month","পূর্ববর্তী পর্যবেক্ষিত মাস"),L("Next observed month","পরবর্তী পর্যবেক্ষিত মাস"),L("Interpolated NDVI","ইন্টারপোলেটেড NDVI"),L("Interpolated EVI","ইন্টারপোলেটেড EVI"),L("Valid MODIS composites","বৈধ MODIS কম্পোজিট"),L("Valid pixels before interpolation","ইন্টারপোলেশনের আগে বৈধ পিক্সেল")]; st.dataframe(d[[x for x in keep if x in d.columns]].round(4),hide_index=True,use_container_width=True)
    with st.expander(L("Strict QA0 vs QA01 audit","Strict QA0 বনাম QA01 অডিট")):
        d=qa.rename(columns={"metric":L("Metric","পরিমাপক"),"Strict_QA0":"Strict QA0","QA01":"QA01","note":L("Interpretation","ব্যাখ্যা")}); st.dataframe(d,hide_index=True,use_container_width=True)

    st.markdown(f"#### {L('Method notes and transparent rules','পদ্ধতি ও স্বচ্ছ নিয়ম')}")
    st.markdown(L("""
- CHIRPS v3 pentad precipitation is aggregated to monthly upazila-polygon means.
- MODIS MOD13Q1 NDVI/EVI is scaled by 0.0001; primary series accepts SummaryQA 0 or 1, with strict QA0 retained for sensitivity/reference.
- Monthly NDVI/EVI uses valid-pixel-weighted 16-day composites; seven fully missing upazila-months are linearly interpolated and flagged.
- `MODIS coverage proxy` is a relative diagnostic, not exact land-area coverage. The ≥50% filter is a dashboard rule, not an official MODIS threshold.
- Rainfall and vegetation z-scores are standardized within each upazila and calendar month using the full finalized 2001–2025 series.
- Lag analysis matches rainfall at month t with vegetation at t, t+1, t+2 or t+3 on the complete calendar sequence.
- Recovery analysis is exploratory and uses a transparent dashboard rule, not an agronomic standard.
- BMDA service-area ratios combine BMDA reported areas with a fixed WARPO irrigable-area baseline and are diagnostic only.
- Final welfare `U` is not estimated.
""","""
- CHIRPS v3 পেন্টাড বৃষ্টিপাতকে মাসিক উপজেলা-পলিগন গড়ে রূপান্তর করা হয়েছে।
- MODIS MOD13Q1 NDVI/EVI-তে 0.0001 স্কেল; প্রধান সিরিজে SummaryQA 0 বা 1, strict QA0 সংবেদনশীলতা/রেফারেন্স হিসেবে রাখা হয়েছে।
- মাসিক NDVI/EVI বৈধ-পিক্সেল-ওজনযুক্ত ১৬-দিনের কম্পোজিট ব্যবহার করে; সম্পূর্ণ অনুপস্থিত ৭ উপজেলা-মাস লিনিয়ার ইন্টারপোলেট ও ফ্ল্যাগ করা হয়েছে।
- `MODIS coverage proxy` আপেক্ষিক নির্ণায়ক, সঠিক ভূমি-এলাকা কভারেজ নয়। ≥৫০% ফিল্টার ড্যাশবোর্ড নিয়ম, সরকারি MODIS সীমা নয়।
- বৃষ্টি ও উদ্ভিদ z-স্কোর প্রতিটি উপজেলা ও ক্যালেন্ডার মাসে পূর্ণ ২০০১–২০২৫ চূড়ান্ত সিরিজ থেকে স্ট্যান্ডার্ডাইজ করা।
- বিলম্ব বিশ্লেষণে t মাসের বৃষ্টির সাথে পূর্ণ ক্যালেন্ডার ধারায় t, t+1, t+2 বা t+3 মাসের উদ্ভিদ মান মিলানো হয়।
- পুনরুদ্ধার বিশ্লেষণ অনুসন্ধানমূলক এবং স্বচ্ছ ড্যাশবোর্ড নিয়ম ব্যবহার করে, কৃষিবৈজ্ঞানিক মান নয়।
- BMDA সেবা-এলাকা অনুপাত BMDA প্রতিবেদিত এলাকা ও স্থির WARPO সেচযোগ্য ভিত্তি মিলিয়ে তৈরি এবং শুধু নির্ণায়ক।
- চূড়ান্ত কল্যাণ `U` অনুমান করা হয়নি।
"""))

    st.markdown(f"#### {L('Terminology glossary','পরিভাষা অভিধান')}")
    gl=pd.DataFrame([["NDVI",L("Satellite greenness indicator; not direct crop yield.","স্যাটেলাইট সবুজত্ব সূচক; সরাসরি ফসল ফলন নয়।")],["EVI",L("Alternative satellite vegetation indicator.","বিকল্প স্যাটেলাইট উদ্ভিদ সূচক।")],[L("Rainfall anomaly","বৃষ্টিপাতের বিচ্যুতি"),L("Difference from the normal value for the same calendar month, expressed here as a z-score.","একই ক্যালেন্ডার মাসের স্বাভাবিক মান থেকে পার্থক্য; এখানে z-স্কোর হিসেবে।")],[L("Z-score","Z-স্কোর"),L("Standard deviations above/below the historical monthly mean.","ঐতিহাসিক মাসিক গড় থেকে কত স্ট্যান্ডার্ড ডিভিয়েশন উপরে/নিচে।")],["DTW",L("Deep Tube Well for groundwater irrigation.","ভূগর্ভস্থ পানি-সেচের গভীর নলকূপ।")],["LLP",L("Low Lift Pump, generally for lifting surface water.","Low Lift Pump, সাধারণত পৃষ্ঠজল তোলার জন্য।")],[L("Irrigable area","সেচযোগ্য এলাকা"),L("Land considered suitable/available for irrigation in the baseline.","ভিত্তি অনুযায়ী সেচের উপযোগী/উপলভ্য জমি।")],[L("Service area","সেবা এলাকা"),L("Reported area served by equipment; may not be unique irrigated land.","যন্ত্রের প্রতিবেদিত সেবা এলাকা; স্বতন্ত্র সেচকৃত জমি নাও হতে পারে।")],[L("Groundwater depth","ভূগর্ভস্থ পানির গভীরতা"),L("Depth from ground surface to groundwater table.","ভূ-পৃষ্ঠ থেকে ভূগর্ভস্থ পানিস্তর পর্যন্ত গভীরতা।")],[L("Dry shock","শুষ্ক ধাক্কা"),L("A month below the selected rainfall-anomaly threshold.","নির্বাচিত বৃষ্টি-বিচ্যুতি সীমার নিচের মাস।")],[L("Coverage proxy","কভারেজ প্রক্সি"),L("Relative valid-pixel diagnostic, not exact land percentage observed.","আপেক্ষিক বৈধ-পিক্সেল নির্ণায়ক; পর্যবেক্ষিত জমির সঠিক শতাংশ নয়।")],[L("Derived stress score","ডেরাইভড স্ট্রেস স্কোর"),L("Illustrative 0–100 ordinal comparison from stress-category counts; not official IWM WSI.","চাপ-শ্রেণির সংখ্যা থেকে উদাহরণমূলক ০–১০০ অর্ডিনাল তুলনা; সরকারি IWM WSI নয়।")],[L("Productivity proxy","উৎপাদনশীলতার প্রক্সি"),L("Indirect indicator used when direct focal-upazila crop yield is unavailable.","ফোকাল উপজেলার সরাসরি ফসল ফলন না থাকলে ব্যবহৃত পরোক্ষ সূচক।")],[L("Resilience","সহনশীলতা"),L("Ability of vegetation to withstand and return toward normal after adverse climate conditions.","প্রতিকূল জলবায়ুতে উদ্ভিদের টিকে থাকা ও স্বাভাবিকতার দিকে ফিরে আসার ক্ষমতা।")]],columns=[L("Term","পরিভাষা"),L("Plain-language meaning","সহজ অর্থ")]); st.dataframe(gl,hide_index=True,use_container_width=True)

    st.markdown(f"#### {L('Downloads','ডাউনলোড')}")
    export=f.copy(); export["Upazila_display"]=export.upazila.map(uname); st.download_button(L("Download currently filtered monthly data","বর্তমানে ফিল্টার করা মাসিক ডেটা ডাউনলোড"),export.to_csv(index=False).encode("utf-8-sig"),file_name="barind_filtered_monthly_data.csv",mime="text/csv",use_container_width=True)
    files=[(L("V0.2 monthly modeling panel","V0.2 মাসিক মডেলিং প্যানেল"),"v02_monthly_panel.csv"),(L("V0.1 BMDA technology panel","V0.1 BMDA প্রযুক্তি প্যানেল"),"v01_bmda_t_panel.csv"),(L("V0.1 WARPO baseline","V0.1 WARPO ভিত্তি"),"v01_warpo_baseline.csv"),(L("V0.1 scorecard","V0.1 স্কোরকার্ড"),"v01_scorecard.csv"),(L("V0.1 BBS productivity context","V0.1 BBS উৎপাদনশীলতা প্রেক্ষাপট"),"v01_bbs_productivity_context.csv"),(L("MODIS interpolation audit","MODIS ইন্টারপোলেশন অডিট"),"modis_interpolation_audit.csv"),(L("MODIS QA comparison audit","MODIS QA তুলনা অডিট"),"modis_qa_comparison_audit.csv")]; dc=st.columns(2)
    for i,(lab,name) in enumerate(files):
        with dc[i%2]: st.download_button(lab,(DATA/name).read_bytes(),file_name=name,mime="text/csv",use_container_width=True,key="d_"+name)
    st.markdown(f"#### {L('Suggested citation','প্রস্তাবিত উদ্ধৃতি')}"); st.code("Shaikh Afnan Birahim (2026). Barind Technology & Resilience Dashboard: Afnan Agricultural Technology & Resilience Model, Version 1.0.")

st.markdown("<div class='soft'></div>",unsafe_allow_html=True)
st.caption(L(f"Barind Technology & Resilience Dashboard V{VERSION} • Mahadebpur & Sapahar, Naogaon • Evidence → Diagnosis → Priority → Action → Monitoring. Recommendations require appropriate technical/authority validation before implementation.",f"বরেন্দ্র প্রযুক্তি ও সহনশীলতা ড্যাশবোর্ড V{VERSION} • মহাদেবপুর ও সাপাহার, নওগাঁ • প্রমাণ → রোগনির্ণয় → অগ্রাধিকার → করণীয় → পর্যবেক্ষণ। বাস্তবায়নের আগে যথাযথ কারিগরি/কর্তৃপক্ষ যাচাই প্রয়োজন।"))
